# Etapa 1: Construcción
FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build # Esto genera los archivos en /app/dist

# Etapa 2: Servidor de desarrollo
FROM node:20-alpine

WORKDIR /app

COPY --from=build /app /app

RUN npm install -g vite

EXPOSE 3001

CMD ["vite", "preview", "--port", "3001", "--host"]
