version: '3.8'

services:
  # Servicio de la base de datos PostgreSQL
  db:
    image: postgres:alpine
    container_name: postgres_task_app
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "taskdb"]
      interval: 10s
      retries: 5
      start_period: 30s

  # Servicio del backend (Node.js API)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    env_file:
      - ./backend/.env  # Cargar el archivo .env con la variable DATABASE_URL
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend-network
    command: >
      sh -c "
        npm install &&
        npx prisma migrate deploy &&
        npm run dev
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      retries: 5
      start_period: 30s
  # Servicio del frontend (React con Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - frontend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
